### ISSUE TITLE
Hope to fix no response problem

### ISSUE THREAD

**Issue by wdpm** [crwgregory/NoteWidgets#1]
First,thanks to your Notewidget example.But I  found a problem about it.
Procedure:
1.run your app in my android emulator (android 5.0).
2.create a new widget on desktop.
3.tonch it to jump to NoteActivity,type title_text and body_text,then save.
4.shut down  and restart emulator.
5.touch the previous widget,**it didn't jump to NoteActivity.No response.**
Solution:
Edit WidgetHelper.java in line 36.
`Intent intent = new Intent(context.getApplicationContext(), context.getClass());`
to
`Intent intent = new Intent(context.getApplicationContext(), NoteActivity.class);`
Then repeat above procedure.It works.
@crwgregory

**Comment by mtio** [comment]
:D Wow thanks! I have been having the same trouble! 

I didn't know anyone was working with this app haha. :P 

I'll implement the change soon.

**Comment by mtio** [comment]
If you want to make a pull request with the change I can merge from there. Thanks!

**Comment by mtio** [comment]
#2
